### ISSUE TITLE
NUCLEO-F302R8 Connection settings and test methods Please confirm. Please ~~~ 

### ISSUE THREAD

**Issue by bluekaka** [OPALESECURITY/hardsploit-gui#5]
hello hardsploit team

I am the link below to jam NUCLEO-F302R8 Development Board on the mbed os in the provision of st-link2 debugger used to do the top left of the SWD interface through debug it is possible that the information found after hardsploit through binary read / write tests try to help is needed.

Motif finding out the facts that can be connected to an external debugger interface on the link below hardsploit

Motif links: move

How I tried to 3.3v power supply via pin 1 on the CN4 hardsploit
And when I tried to add additional features over the next components I have not been able to find the relevant swd.

And tried to swd scan device it is not recognized.

Ask for answers.

NUCLEO-F302R8 user guide 

Debug connector CN4 (SWD)
Pin CN4 Designation
1 VDD_TARGET VDD from application
2 SWCLK SWD clock
3 GND Ground
4 SWDIO SWD data input/output
5 NRST RESET of target MCU
6 SWO Reserved

mcu datasheet : STM32F030x8

**Comment by julienmoinard** [comment]
Hello,  Hardsploit is only compliant with stm32F1xx famility for the moment, I have a beta version where you can change the CPUID etc to be compliant with but you need to do that every time you have another part. You need to change flash settings, begin address in your case with STM32F030x8 the start address of the flash is 0 instead of STM32F1xx it is 0x08000000 and size of address, if the flash is to big you need to use 2 banks etc ). It is to complicate and it is exactly the purpose of openocd project.

So I change my idea about Hardsploit and SWD, I prefer to develop a driver to be compliant with openocd project !

My advice, use your onboard stlinkV2  with openocd project available here to try do dump and write your data https://github.com/serma-safety-security/openocd

Very soon I will publish on this repository a new version of openocd with hardsploit support (already done but in alpha version, read write ok but not all gdb functions).

But you can detect your device with hardsploit if you remove SWD jumper to connect SWDCLK and SWDIO to hardsploit.

Best regards,
Julien.

**Comment by bluekaka** [comment]
Hello,  
thank you Julien !!!
hava a nice day!!!!
